---
name: ðŸ¤– format descriptors

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BRANCH: "master"

jobs:
  format:
    name: format descriptors
    runs-on: public-ledgerhq-shared-small
    timeout-minutes: 60
    steps:

      - name: Checkout
        timeout-minutes: 10
        uses: actions/checkout@v5

      - name: Get date
        timeout-minutes: 10
        run: echo "CURRENT_DATE=$(date +"%Y-%m-%d %H:%M")" >> $GITHUB_ENV

      - name: Setup python
        timeout-minutes: 10
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Login to Ledger JFrog
        timeout-minutes: 10
        uses: LedgerHQ/actions-security/actions/jfrog-login@actions/jfrog-login-1

      - name: Setup pip
        timeout-minutes: 10
        run: jf pipc --global --repo-resolve=virtual-pypi-prod-green

      - name: Install ERC-7730 library
        timeout-minutes: 10
        run: jf pip install erc7730

      - name: Format ERC-7730 descriptors
        timeout-minutes: 10
        run: erc7730 format

      - name: Check changes
        id: changes
        timeout-minutes: 10
        shell: bash
        run: |
          [[ -n "$(git status -s)" ]] && echo "changes=true" >> $GITHUB_OUTPUT || true

      - name: Open pull request
        if: ${{ !cancelled() && steps.changes.outputs.changes == 'true' }}
        timeout-minutes: 10
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
          author: ${{ secrets.CI_BOT_USERNAME }} <${{ secrets.CI_BOT_USERNAME }}@users.noreply.github.com>
          branch: ${{ env.BRANCH }}-format-descriptors
          base: ${{ env.BRANCH }}
          delete-branch: false
          commit-message: 'chore: format descriptors - ${{ env.CURRENT_DATE }}'
          title: 'chore: format descriptors - ${{ env.CURRENT_DATE }}'
          body: ${{ steps.submodules.outputs.prBody }}
          draft: false
          signoff: false
